console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
auto_upgrade = true
final_space = true

[palette]
  air-force-blue = '#698996'
  black = '#262B44'
  blue = '#4B95E9'
  cambridge-blue = '#97B1A6'
  carribean-current = '#407076'
  feldgrau = '#466060'
  green = '#59C9A5'
  kinda-blue = '#59858b'
  light-pink = '#d57b9a'
  lighter-green = '#c7f0e1'
  orange = '#F07623'
  puce = '#C581A3'
  purple = '#750EEB'
  quinacridone-magenta = '#8E4162'
  red = '#D81E5B'
  tea-rose = '#EBBAB9'
  text = '#494D64'
  timberwolf = '#C9C5BA'
  white = '#E0DEF4'
  yellow = '#F3AE35'

[secondary_prompt]
  template = '<p:yellow,transparent> </><,p:yellow> > </><p:text,transparent> </> '
  foreground = 'p:text'
  background = 'transparent'

[transient_prompt]
  template = '<#8AADF4,transparent></><,#8AADF4> {{ .Folder }} </><#8AADF4,transparent></>'
  foreground = 'p:text'
  background = 'p:tea-rose'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = '{{if atoi .Env.COLS | lt 75}} {{ if .SSHSession }} {{ end }}{{ .UserName }} {{end}}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = '#8AADF4'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{if atoi .Env.COLS | lt 75}}  {{ path .Path .Location }}{{end}}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = '#B7BDF8'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'unique'

  [[blocks.segments]]
    template = '{{if atoi .Env.COLS | gt 75}}{{.Path}}{{end}}'
    foreground = 'p:tea-rose'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

  [[blocks.segments]]
    template = '{{if atoi .Env.COLS | lt 75}} {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} {{end}}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:cambridge-blue'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:text{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:text{{ end }}', '{{ if gt .Ahead 0 }}p:text{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#e0d1cd{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}p:lighter-green{{ end }}', '{{ if gt .Behind 0 }}p:kinda-blue{{ end }}']

    [blocks.segments.properties]
      branch_max_length = 25
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '{{if atoi .Env.COLS | lt 75}}  {{end}}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:timberwolf'
    type = 'root'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '<transparent,background></>'
    template = '{{if atoi .Env.COLS | lt 75}} {{ if gt .Code 0 }}{{ else }}{{ end }}{{end}}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = '#F5BDE6'
    type = 'status'
    style = 'powerline'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{if atoi .Env.COLS | gt 75 }}>{{end}}'
    foreground = 'p:purple'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = '{{if atoi .Env.COLS | lt 75}}  {{ .Full }} {{end}}'
    foreground = '#193549'
    powerline_symbol = ''
    background = '#99908a'
    type = 'rust'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{if atoi .Env.COLS | lt 75}}  {{ .Full }} {{end}}'
    foreground = '#100e23'
    powerline_symbol = ''
    background = '#906cff'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'

  [[blocks.segments]]
    template = '{{if atoi .Env.COLS | lt 75}} {{ .Latest }}{{end}}'
    type = 'upgrade'
    style = 'powerline'
