"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[[blocks]]
type = "prompt"
alignment = "left"
# Debug COLS
# [[blocks.segments]]
# type="text"
# style="plain"
# foreground="p:white"
# template="{{ .Env.COLS }} {{if atoi .Env.COLS | lt 75}} true {{else}} false {{end}}"

[[blocks.segments]]
type = "session"
style = "diamond"
foreground = "p:black"
background = "p:yellow"
leading_diamond = ""
trailing_diamond = ""
template = "{{if atoi .Env.COLS | lt 75}} {{ if .SSHSession }} {{ end }}{{ .UserName }} {{end}}"

[[blocks.segments]]
type = "ytm"
style = "diamond"
leading_diamond = ""
trailing_diamond = ""
foreground = "p:white"
background = "#ff0000"
template = "{{if atoi .Env.COLS | lt 75}} {{ .Icon }}{{ if ne .Status \"stopped\"}}{{ if lt (len .Track) 18 }}{{ .Track }}{{ else }}...{{ end }}{{ end }}{{end}}"

[blocks.segments.properties]
paused_icon = "󰏤 "

[[blocks.segments]]
type = "path"
style = "powerline"
powerline_symbol = ""
foreground = "p:white"
background = "p:orange"
template = "{{if atoi .Env.COLS | lt 75}}  {{ path .Path .Location }}{{end}}"

[blocks.segments.properties]
style = "unique"

[[blocks.segments]]
type="path"
style="plain"
foreground="p:purple"
template = "{{if atoi .Env.COLS | gt 75}}{{.Path}}{{end}}"

[blocks.segments.properties]
style="folder"

[[blocks.segments]]
type = "git"
style = "powerline"
powerline_symbol = ""
foreground = "p:black"
foreground_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}",
    "{{ if gt .Ahead 0 }}p:white{{ end }}",
]
background = "p:green"
background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
    "{{ if gt .Ahead 0 }}#49416D{{ end }}",
    "{{ if gt .Behind 0 }}#7A306C{{ end }}",
]
template = "{{if atoi .Env.COLS | lt 75}} {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} {{end}}"

[blocks.segments.properties]
branch_max_length = 25
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
type = "root"
style = "powerline"
powerline_symbol = ""
foreground = "p:white"
background = "p:yellow"
template = "{{if atoi .Env.COLS | lt 75}}  {{end}}"

[[blocks.segments]]
type = "executiontime"
style = "diamond"
foreground = "p:black"
background = "p:white"
leading_diamond = ""
trailing_diamond = ""
template = "{{if atoi .Env.COLS | lt 75}}󱎫 {{ .FormattedMs }}{{end}}"

[blocks.segments.properties]
threshhold = 2000
style = "roundrock"

[[blocks.segments]]
type = "status"
style = "diamond"
foreground = "p:white"
background = "p:blue"
background_templates = ["{{ if gt .Code 0 }}p:red{{ end }}"]
leading_diamond = "<transparent,background></>"
trailing_diamond = ""
template = "{{if atoi .Env.COLS | lt 75}} {{ if gt .Code 0 }}{{ else }}{{ end }}{{end}}"

[blocks.segments.properties]
always_enabled = true

[[blocks.segments]]
type="text"
style="plain"
foreground="p:purple"
template="{{if atoi .Env.COLS | gt 75 }}>{{end}}"

[[blocks]]
type = "rprompt"

[[blocks.segments]]
type = "rust"
style = "powerline"
powerline_symbol = ""
foreground = "#193549"
background = "#99908a"
template = "{{if atoi .Env.COLS | lt 75}}  {{ .Full }} {{end}}"

[[blocks.segments]]
type = "python"
style = "powerline"
powerline_symbol = ""
foreground = "#100e23"
background = "#906cff"
template = "{{if atoi .Env.COLS | lt 75}}  {{ .Full }} {{end}}"

[blocks.segments.properties]
display_mode = "files"

[[blocks.segments]]
type = "time"
style = "powerline"
powerline_symbol = ""
foreground = "#100e23"
background = "#72967e"
template = "{{if atoi .Env.COLS | lt 75}} {{ .CurrentDate | date .Format }} {{end}}"

[blocks.segments.properties]
time_format = "3:04:05 PM"
powerline_symbol = ""
background = "#919672"
foreground = "#2f3315"

[[blocks.segments]]
type="upgrade"
style="powerline"
template="{{if atoi .Env.COLS | lt 75}} {{ .Latest }}{{end}}"

[[tooltips]]
type = "az"
tips = ["az"]
style = "diamond"
foreground = "p:white"
background = "p:blue"
leading_diamond = ""
trailing_diamond = ""
template = "{{if atoi .Env.COLS | lt 75}}  {{ .Name }} {{end}}"

[tooltips.properties]
display_default = true

[transient_prompt]
foreground = "p:white"
background = "transparent"
template = "<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></>"

[secondary_prompt]
foreground = "p:black"
background = "transparent"
template = "<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> "

[palette]
black = "#262B44"
blue = "#4B95E9"
green = "#59C9A5"
orange = "#F07623"
red = "#D81E5B"
white = "#E0DEF4"
yellow = "#F3AE35"
purple = "#750EEB"
